### ISSUE TITLE
Uneven framerate anywhere within game

### ISSUE THREAD

**Issue by mlindner** [arescentral/antares#217] opened 2018-05-06 04:03 UTC
While playing there is a constant uneven framerate where it will "freeze" every roughly half second and then resume normal framerate.

Mac OS X 10.10 with Integrated and Discrete GPU.

**Comment by sfiera** [comment] 2018-05-06 05:34
Antares has problems with discrete GPUs (#154). I haven’t been able to improve the situation, as I don’t have a machine with a discrete GPU to test on. Could you:
1. Try [gfxCardStatus](https://gfx.io/) with integrated graphics, to confirm that the problem is the same as #154.
2. Try [an experimental build](http://downloads.arescentral.org/Antares/antares-mac-dev.zip) from the [gpu branch](https://github.com/sfiera/antares/tree/gpu).

**Comment by sfiera** [comment] 2018-05-06 13:32
It’s very likely I’m doing something inefficient. I’m not a graphics person, and I wrote the current code as a port of a software renderer, where things were done very differently.

Anyway, since this seems to be the same as #154, let’s move discussion there.

**Comment by sfiera** [comment] 2018-05-06 13:33
Duplicate of #154
(is this how Github does it?)

**Closed by sfiera** 2018-05-06 13:33 UTC
